#server:
#  port: 8083
spring:
  application:
    name: 3_Customer_Service
  config:
    import: configserver:http://localhost:8084
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/customer_schema
#    username: root
#    password: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#  sql:
#    init:
#      mode: always

